ollama:
  host: "http://localhost"
  port: 11434
  model: "qwen3:4b"
  embedding_model: "nomic-embed-text"
  temperature: 0.7
  max_tokens: 2048

vector_store:
  type: "chromadb"
  path: "./data/chroma_db"
  collection_name: "db_schema_docs"

data:
  schema_path: "./data/schema_docs"
  file_extensions: [".md"]

agent:
  verbose: true
  max_context_messages: 5
  system_prompt: |
    You are a helpful AI assistant specialized in database queries and information retrieval.
    You can search through documentation and execute read-only SQL queries to help users.
    Always prioritize data security and never execute data modification queries.

sql:
  allow_write: false
  connection_string: ""  # To be configured based on actual database
  max_results: 100

logging:
  level: "INFO"
  file: "./logs/agent.log"
  max_bytes: 10485760  # 10MB
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

rag:
  chunk_size: 512
  chunk_overlap: 50
  top_k: 5